name: pure_ftp_server
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/crifurch/pure_ftp_server

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  yaml: ^3.1.2
